### DISCUSSION TITLE
"Best practice" when tagging?

### DISCUSSION THREAD

**Discussion by applejag** [srid/neuron#536] [General]
I've read some guides about zettelkasten and the generic concept is that

- Your tags should reflect your queries when looking for the information

I'm new to note taking, zettelkasten, and neuron. But with a week practice I think I'm starting to get the hang of it.

Here's an example from a permanent note of mine:

```yaml
---
date: 2021-01-20T21:30
tags: 
  - linux/how does memory work in linux
  - linux/what types of memory exists in linux
---
```

To not make too big assumptions of how it must be done, but rather "you do it your way" kind of perspective, my questions is:

- Do you do write tags in a similar way? Has it been benifitial to you? Are you acustomed to a different format that you've found more giving?
