### DISCUSSION TITLE
Windows Support

### DISCUSSION THREAD

**Discussion by levirs565** [srid/neuron#584] [Installation]
Neuron is great project. However, it does not support Windows. I have been trying to port Neuron to Windows. Unfortunately Neuron is using NixPkgs. I am trying to add Stack support for Neuron. My initial `stack.yaml` is this:

```yaml
resolver: lts-17.6

extra-deps:
- github: srid/directory-contents
  commit: 0d3f1d5c86063232a3ccf081d9be143eb2ff1466
- github: srid/pandoc-link-context
  commit: ff8d1de662d4b2d3be0553d93f51a67a1696ced7
- github: reflex-frp/reflex-fsnotify
  commit: cca674623b797dd423421dec0f1da952a1d1f36d
- github: srid/reflex-dom-pandoc
  commit: 63ff62ee9c7f4a8c231db16bb91b858c8a39aebd
# - aeson-gadt-th-0.2.5.0
# - th-abstraction-0.3.2.0
# - dependent-map-0.4.0.0
# - dependent-sum-0.7.1.0
# - constraints-extras-0.3.0.2
# - dependent-sum-template-0.1.0.3
- reflex-0.8.0.0
# - reflex-dom-core-0.6.1.0
# - template-haskell
# - dependent-sum-template-0.1.0.3
# - constraints-extras-0.3.0.2
```

However, Its fail and show this error:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for directory-contents-0.2.0.0:
    witherable must match >=0.3 && <0.5, but the stack configuration has no specified version  (latest matching version is 0.4.1)
needed due to neuron-1.9.25.0 -> directory-contents-0.2.0.0

In the dependencies for neuron-1.9.25.0:
    aeson-gadt-th must match >=0.2.5.0, but the stack configuration has no specified version  (latest matching version is 0.2.5.0)
    constraints-extras needed, but the stack configuration has no specified version  (latest matching version is 0.3.0.2)
    dependent-map needed, but the stack configuration has no specified version  (latest matching version is 0.4.0.0)
    dependent-sum needed, but the stack configuration has no specified version  (latest matching version is 0.7.1.0)
    dependent-sum-aeson-orphans must match >=0.2.1.0, but the stack configuration has no specified version  (latest matching version is 0.3.0.0)
    dependent-sum-template needed, but the stack configuration has no specified version  (latest matching version is 0.1.0.3)
    lsp needed, but the stack configuration has no specified version  (latest matching version is 1.1.1.0)
    reflex-dom-core needed, but the stack configuration has no specified version  (latest matching version is 0.6.1.0)
    shower needed, but the stack configuration has no specified version  (latest matching version is 0.2.0.2)
    which needed, but the stack configuration has no specified version  (latest matching version is 0.2)
needed since neuron is a build target.

In the dependencies for reflex-0.8.0.0:
    base-4.14.1.0 from stack configuration does not match >=4.9 && <4.14  (latest matching version is 4.13.0.0)
    constraints-extras must match >=0.3 && <0.4, but the stack configuration has no specified version  (latest matching version is 0.3.0.2)
    dependent-map must match >=0.3 && <0.5, but the stack configuration has no specified version  (latest matching version is 0.4.0.0)
    dependent-sum must match >=0.6 && <0.8, but the stack configuration has no specified version  (latest matching version is 0.7.1.0)
    monoidal-containers must match >=0.6 && <0.7, but the stack configuration has no specified version  (latest matching version is 0.6.0.1)
    patch must match >=0.0.1 && <0.1, but the stack configuration has no specified version  (latest matching version is 0.0.3.2)
    prim-uniq must match >=0.1.0.1 && <0.3, but the stack configuration has no specified version  (latest matching version is 0.2)
    template-haskell-2.16.0.0 from stack configuration does not match >=2.9 && <2.16  (latest matching version is 2.15.0.0)
    witherable must match >=0.3 && <0.4, but the stack configuration has no specified version  (latest matching version is 0.3.5)
needed due to neuron-1.9.25.0 -> reflex-0.8.0.0

In the dependencies for reflex-dom-pandoc-0.7.9.0:
    reflex-dom-core needed, but the stack configuration has no specified version  (latest matching version is 0.6.1.0)
needed due to neuron-1.9.25.0 -> reflex-dom-pandoc-0.7.9.0

In the dependencies for reflex-fsnotify-0.2.1.2:
    base-4.14.1.0 from stack configuration does not match >=4.10 && <4.14  (latest matching version is 4.13.0.0)
needed due to neuron-1.9.25.0 -> reflex-fsnotify-0.2.1.2

Some different approaches to resolving this:

  * Build requires unattainable version of base. Since base is a part of GHC, you most likely need to use a different GHC version with the matching base.

Plan construction failed.
```

I see that `reflex` is not suppor GHC 8.10 because GHC 8.10 is use `base-4.14`. When I read `CHANGELOG` its say that Neuron have been migrated to GHC 8.10. Solution for this problem maybe using GHC 8.9. Is there any solution than this?
